@LuckySpin.Api_HostAddress = http://localhost:5228

GET {{LuckySpin.Api_HostAddress}}/api/Game/test
Accept: application/json

###

POST {{LuckySpin.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
	"email": "player@example.com",
	"password": "testing",
	"playerName": "Player"
}

###

@token = paste-token-from-register-response

GET {{LuckySpin.Api_HostAddress}}/api/account
Authorization: Bearer {{token}}
Accept: application/json

###

POST {{LuckySpin.Api_HostAddress}}/api/Game/spin
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"bet": 10,
	"betType": "classic"
}
